#!/bin/sh
pandoc --template beamer.template \
       --variable institute="TU Darmstadt" \
       --variable subtitle="Paper written by Barthe, Rezk, Russo and Sabelfeld \cite{Barthe07}" \
       -i slides.md -o slides-md.tex
perl -pe 's/\\subsubsection/\\begin{frame}/' -i slides-md.tex
perl -pe 's/\\paragraph/\\end{frame}/' -i slides-md.tex
pdflatex slides-md.tex </dev/null
bibtex slides-md
pdflatex slides-md.tex </dev/null
